#!/bin/sh
# Render the AI contract into every harness's global instruction file.
#
# Sources: shared/AGENTS.md (public) plus dotfiles-mic/AGENTS-MIC.md when the
# private overlay is checked out. They are concatenated into ONE regular file
# per target. Measured 2026-09-09: only Claude Code reads a marker file placed
# one level above a git root (and only CLAUDE.md, never AGENTS.md); codex, grok,
# agy and opencode read nothing above the repo root. So directory-scoped org
# rules are not portable across harnesses, and concatenation is.
#
# SAFETY: every target was previously a symlink into this repo. Opening one for
# writing would truncate shared/AGENTS.md itself. A target is therefore never
# written through: content is rendered to a temp file, copied into the target's
# own directory, unlinked at the destination, then moved into place.
#
# Exit codes: 0 ok | 1 stale targets (--check) or a failed render | 2 usage
# error, missing public source, or a target that cannot be resolved.
set -eu

ROOT=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd -P)
PUBLIC_SRC="$ROOT/shared/AGENTS.md"
MIC_SRC="$ROOT/dotfiles-mic/AGENTS-MIC.md"
RENDERER="$ROOT/scripts/render-contract.sh"

usage() {
    cat <<'EOF'
Usage: scripts/render-contract.sh [--check]

Renders shared/AGENTS.md, plus dotfiles-mic/AGENTS-MIC.md when the private
overlay is present, into each harness's global instruction file.

  --check   List targets whose content is out of date, exit 1. Writes nothing.

A target is skipped when its identity directory does not exist: this script never
creates one. ./install provisions ~/.claude2 (public pass) and ~/.claude-mic
(private overlay pass), so a public-only clone simply has no ~/.claude-mic.
EOF
}

check_only=0
if [ "$#" -gt 1 ]; then
    printf 'render-contract: too many arguments\n' >&2
    usage >&2
    exit 2
fi
case "${1:-}" in
    '') ;;
    --check) check_only=1 ;;
    -h|--help) usage; exit 0 ;;
    *)
        printf 'render-contract: unknown argument: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
esac

if [ ! -f "$PUBLIC_SRC" ]; then
    printf 'render-contract: missing public source: %s\n' "$PUBLIC_SRC" >&2
    exit 2
fi

# identity directory | target file. The identity dir gate mirrors what the
# retired link entries did: install.conf.yaml creates ~/.claude, ~/.claude2,
# ~/.codex, ~/.config/opencode, ~/.gemini/config and ~/.dsh, and the overlay
# creates ~/.claude-mic. A machine without the overlay must not grow a
# ~/.claude-mic, and a machine that has never installed the DeepSeek Harness
# pilot must not grow a ~/.dsh: removing that directory is how the pilot is
# rolled back, and the seventh target then reports skipped by design.
targets() {
    cat <<EOF
$HOME/.claude|$HOME/.claude/CLAUDE.md
$HOME/.claude2|$HOME/.claude2/CLAUDE.md
$HOME/.claude-mic|$HOME/.claude-mic/CLAUDE.md
$HOME/.codex|$HOME/.codex/AGENTS.md
$HOME/.config/opencode|$HOME/.config/opencode/AGENTS.md
$HOME/.gemini/config|$HOME/.gemini/config/plugins/dotfiles/rules/AGENTS.md
$HOME/.dsh|$HOME/.dsh/AGENTS.md
EOF
}

work_dir=$(mktemp -d "${TMPDIR:-/tmp}/render-contract.XXXXXX")
staged=""
# Reached through the trap below, which shellcheck does not follow.
# shellcheck disable=SC2329
cleanup() {
    rm -rf "$work_dir"
    [ -z "$staged" ] || rm -f "$staged"
}
trap cleanup EXIT HUP INT TERM

# cat a source and guarantee exactly one closing newline, so a source without a
# trailing newline cannot glue itself to the separator.
cat_section() {
    cat "$1"
    if [ -n "$(tail -c 1 "$1")" ]; then
        printf '\n'
    fi
}

rendered=$work_dir/contract.md
{
    printf '<!--\n'
    printf 'GENERATED FILE - do not edit this file; edits are lost on the next install.\n'
    printf 'Edit the source(s) below, then run ./install (or %s).\n' "$RENDERER"
    printf 'Source 1: %s\n' "$PUBLIC_SRC"
    if [ -f "$MIC_SRC" ]; then
        printf 'Source 2: %s\n' "$MIC_SRC"
    else
        printf 'Source 2: none (private overlay not checked out)\n'
    fi
    printf 'Rendered: %s\n' "$(date +%Y-%m-%d)"
    printf -- '-->\n\n'
    cat_section "$PUBLIC_SRC"
    if [ -f "$MIC_SRC" ]; then
        printf '\n---\n\n'
        printf '<!-- MIC addendum, rendered from %s -->\n\n' "$MIC_SRC"
        cat_section "$MIC_SRC"
    fi
} >"$rendered"

# Everything a comparison should care about: the whole file except the header's
# render date. That date records when a file was last actually written, so it
# must not by itself make an otherwise identical target look stale tomorrow.
#
# The strip is scoped to the leading HTML comment. A blanket /^Rendered: /d
# would also drop such a line from the contract body, which would both hide a
# real source change and let the same edit in a target pass --check unnoticed.
body() {
    awk '
        NR == 1 { in_header = ($0 == "<!--") }
        in_header && $0 == "-->" { in_header = 0; print; next }
        in_header && /^Rendered: / { next }
        { print }
    ' "$1"
    printf 'X'
}

# Content alone is not freshness: a target left 0600 or 0666 would otherwise be
# reported clean while not matching the mode this script guarantees. 644 is an
# exact-mode match on both BSD and GNU find.
mode_is_644() {
    [ -n "$(find "$1" -perm 644 -print)" ]
}

rendered_body=$(body "$rendered")

n_written=0
n_unchanged=0
n_skipped=0
n_stale=0
n_failed=0

while IFS='|' read -r identity target; do
    [ -n "$target" ] || continue
    if [ ! -d "$identity" ]; then
        n_skipped=$((n_skipped + 1))
        continue
    fi
    if [ -d "$target" ] && [ ! -L "$target" ]; then
        printf 'render-contract: %s is a directory - resolve manually\n' "$target" >&2
        n_failed=$((n_failed + 1))
        continue
    fi
    if [ -f "$target" ] && [ ! -L "$target" ] && mode_is_644 "$target" &&
        [ "$(body "$target")" = "$rendered_body" ]; then
        n_unchanged=$((n_unchanged + 1))
        continue
    fi
    if [ "$check_only" -eq 1 ]; then
        printf 'stale %s\n' "$target"
        n_stale=$((n_stale + 1))
        continue
    fi
    dir=${target%/*}
    if ! mkdir -p "$dir"; then
        n_failed=$((n_failed + 1))
        continue
    fi
    # Staged inside the destination directory so the final move is a rename on
    # one filesystem, and so no partially written contract is ever visible.
    staged=$(mktemp "$dir/.render-contract.XXXXXX")
    cp "$rendered" "$staged"
    chmod 644 "$staged"
    rm -f "$target"
    mv "$staged" "$target"
    staged=""
    printf 'rendered %s\n' "$target"
    n_written=$((n_written + 1))
done <<EOF
$(targets)
EOF

if [ "$check_only" -eq 1 ]; then
    if [ "$n_failed" -gt 0 ]; then
        exit 2
    fi
    printf 'contract: %d up to date, %d stale, %d skipped\n' \
        "$n_unchanged" "$n_stale" "$n_skipped"
    [ "$n_stale" -eq 0 ] || exit 1
    exit 0
fi

printf 'contract: %d rendered, %d unchanged, %d skipped\n' \
    "$n_written" "$n_unchanged" "$n_skipped"
[ "$n_failed" -eq 0 ] || exit 1
exit 0
